"""added foreign key

Revision ID: d3f2c275fee2
Revises: bad09cf17f76
Create Date: 2026-10-09 11:14:33.381066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3f2c275fee2'
down_revision: Union[str, None] = 'bad09cf17f76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'dtr', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dtr', type_='foreignkey')
    # ### end Alembic commands ###
